version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: babylist-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-babylist}
      POSTGRES_USER: ${POSTGRES_USER:-babyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-babypass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U babyuser -d babylist"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: node:20-alpine
    container_name: babylist-app
    working_dir: /tmp/build
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://babyuser:babypass@postgres:5432/babylist}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY:-}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: |
      sh -c "
        apk add --no-cache git openssh openssl &&
        if [ ! -f /app/package.json ]; then
          echo 'Cloning repository...' &&
          git clone https://github.com/vicvasbob/bblist.git /app
        else
          echo 'Repository already exists, pulling latest changes...' &&
          cd /app &&
          git pull origin master || echo 'Pull failed, using existing code'
        fi &&
        cd /app &&
        echo 'Installing ALL npm dependencies (including dev for build)...' &&
        npm install ||
        (echo 'npm install failed, trying npm ci...' && npm ci) ||
        (echo 'Both install methods failed, removing lock and installing...' && 
         rm -f package-lock.json && npm install) &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run build &&
        npm start
      "

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge