version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: babylist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-babylist}
      POSTGRES_USER: ${POSTGRES_USER:-babyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-babypass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U babyuser -d babylist"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: node:20-alpine
    container_name: babylist-app
    working_dir: /tmp/build
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://babyuser:babypass@postgres:5432/babylist}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY:-}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Installing system dependencies...' &&
        apk add --no-cache git openssh openssl &&
        echo 'Preparing app directory...' &&
        rm -rf /app &&
        mkdir -p /app &&
        echo 'Cloning repository fresh...' &&
        git clone https://github.com/vicvasbob/bblist.git /app &&
        cd /app &&
        echo 'Installing ALL npm dependencies (including dev for build)...' &&
        echo 'Current package.json dependencies:' &&
        cat package.json | grep -A 20 '\"dependencies\"' &&
        npm install ||
        (echo 'npm install failed, trying npm ci...' && npm ci) ||
        (echo 'Both install methods failed, removing lock and installing...' && 
         rm -f package-lock.json && npm install) &&
        echo 'Verifying TailwindCSS installation:' &&
        npm list tailwindcss || echo 'TailwindCSS not found!' &&
        echo 'Generating Prisma client...' &&
        npx prisma generate &&
        echo 'Running database migrations...' &&
        npx prisma migrate deploy &&
        echo 'Building Next.js application...' &&
        npm run build &&
        echo 'Removing dev dependencies to save space...' &&
        npm prune --production &&
        echo 'Starting production server...' &&
        npm start
      "

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge