version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: babylist
      POSTGRES_USER: babyuser
      POSTGRES_PASSWORD: babypass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U babyuser -d babylist"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: https://github.com/vicvasbob/bblist.git
      dockerfile: Dockerfile.production
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://babyuser:babypass@postgres:5432/babylist
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "npx prisma migrate deploy && node server.js"

volumes:
  db_data: